version: '3'

services:
    file_secure:
        build: .
        ports:
            - "8000:8000"
        volumes: 
            - ./file_secure:/file_secure
        command: >
            sh -c "python manage.py runserver 0.0.0.0:8000"
        tty: true
        stdin_open: true
        depends_on: 
            - db
        environment:
            DB_HOST : ${DB_HOST_NAME}
            DB_NAME : ${DB_DATABASE_NAME}
            DB_PASSWORD : ${DB_PASS}
            DB_USER : ${DB_USER_NAME}
    
    db:
        image: mysql:8.0.20
        command: --default-authentication-plugin=mysql_native_password
        volumes:
            - "/var/lib/docker/volumes/file_secure/database:/var/lib/mysql"
        ports:
            - "3306:3306"
        environment: 
            MYSQL_DATABASE : ${DB_DATABASE_NAME}
            MYSQL_USER : ${DB_USER_NAME}
            MYSQL_PASSWORD : ${DB_PASS}
            MYSQL_ROOT_PASSWORD : ${DB_PASS}
