version: '3'

services:
    file_secure:
        build: .
        ports:
            - "8000:8000"
        volumes: 
            - ./file_secure:/file_secure
        command: >
            sh -c "python manage.py runserver 0.0.0.0:8000"
