# Generated by Django 3.0.5 on 2020-04-14 16:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rename',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=200)),
                ('filename', models.CharField(max_length=50)),
                ('time', models.DateTimeField(auto_now=True)),
                ('username', models.CharField(max_length=50)),
                ('operationType', models.CharField(max_length=20)),
                ('renameTo', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=models.SET(models.CharField(max_length=50)), to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=200)),
                ('filename', models.CharField(max_length=50)),
                ('time', models.DateTimeField(auto_now=True)),
                ('username', models.CharField(max_length=50)),
                ('moveTo', models.CharField(max_length=50)),
                ('operationType', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=models.SET(models.CharField(max_length=50)), to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Download',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=200)),
                ('filename', models.CharField(max_length=50)),
                ('time', models.DateTimeField(auto_now=True)),
                ('username', models.CharField(max_length=50)),
                ('operationType', models.CharField(max_length=20)),
                ('multiple', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=models.SET(models.CharField(max_length=50)), to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Delete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=200)),
                ('filename', models.CharField(max_length=50)),
                ('time', models.DateTimeField(auto_now=True)),
                ('username', models.CharField(max_length=50)),
                ('multiple', models.BooleanField()),
                ('operationType', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=models.SET(models.CharField(max_length=50)), to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Create',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=200)),
                ('filename', models.CharField(max_length=50)),
                ('time', models.DateTimeField(auto_now=True)),
                ('username', models.CharField(max_length=50)),
                ('private', models.BooleanField()),
                ('operationType', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=models.SET(models.CharField(max_length=50)), to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
