# Generated by Django 3.0.5 on 2020-04-15 12:47

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('updates', '0002_auto_20200415_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='create',
            name='filename',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='create',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='create',
            name='user',
            field=models.ForeignKey(on_delete=models.SET(models.CharField(max_length=255)), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='create',
            name='username',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='delete',
            name='filename',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='delete',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='delete',
            name='user',
            field=models.ForeignKey(on_delete=models.SET(models.CharField(max_length=255)), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='delete',
            name='username',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='download',
            name='filename',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='download',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='download',
            name='user',
            field=models.ForeignKey(on_delete=models.SET(models.CharField(max_length=255)), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='download',
            name='username',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='move',
            name='filename',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='move',
            name='moveTo',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='move',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='move',
            name='user',
            field=models.ForeignKey(on_delete=models.SET(models.CharField(max_length=255)), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='move',
            name='username',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='rename',
            name='filename',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='rename',
            name='renameTo',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='rename',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='rename',
            name='user',
            field=models.ForeignKey(on_delete=models.SET(models.CharField(max_length=255)), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rename',
            name='username',
            field=models.CharField(max_length=255),
        ),
    ]
