# Generated by Django 3.0.5 on 2020-04-18 08:00

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('updates', '0003_auto_20200415_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='create',
            name='private',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='delete',
            name='multiple',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='download',
            name='multiple',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=200)),
                ('filename', models.CharField(max_length=255)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('username', models.CharField(max_length=255)),
                ('isFolder', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=models.SET(models.CharField(max_length=255)), to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
