# Generated by Django 3.0.5 on 2020-04-18 12:18

from django.db import migrations, models
import updates.models


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0004_auto_20200418_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='file_path',
            field=models.FileField(default='../media/', upload_to=updates.models.get_file_upload_path),
        ),
    ]
